; PlatformIO Project Configuration File
; Single-board mode (barometer node only)

[env:barometer_node]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	Wire
	ArduinoJson
	adafruit/Adafruit BMP3XX Library
	adafruit/Adafruit BusIO
	adafruit/Adafruit Unified Sensor
extra_scripts = pre:prebuild.py

[env:barometer_node_s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
	Wire
	ArduinoJson
	adafruit/Adafruit BMP3XX Library
	adafruit/Adafruit BusIO
	adafruit/Adafruit Unified Sensor
build_flags =
	-D BARO_I2C_SDA_PIN=41
	-D BARO_I2C_SCL_PIN=42
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:prebuild.py
